# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print("My numpy version:", np.__version__)
np.show_config()

My numpy version: 1.22.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macr

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
test = np.array([1, 2, 3])

print("Memory size of any array in bytes:", test.size * test.itemsize)

Memory size of any array in bytes: 24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [38]:
%run `python -c "import numpy as np; np.info(np.add)"`

Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
test = np.array([1, 2, 3, 4, 5])

test_reverse = test[::-1]

print(test)
print(test_reverse)

[1 2 3 4 5]
[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
example = np.array([1, 2, 0, 0, 4, 0])

print(example.nonzero())

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
identity_matrix = np.arange(9).reshape(3, 3)

print(identity_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
three_D_array = np.random.random([3, 3, 3])

print(three_D_array)

[[[0.92888325 0.64951289 0.01454439]
  [0.73891608 0.78417088 0.43894159]
  [0.21346645 0.32650667 0.92099759]]

 [[0.26766605 0.93715657 0.55873579]
  [0.94716187 0.84626043 0.37057554]
  [0.2058716  0.45875341 0.88279698]]

 [[0.58064256 0.17891853 0.63717723]
  [0.05180889 0.17456287 0.31298188]
  [0.38141002 0.01995524 0.64943989]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
random_array = np.random.random([10, 10])
mini_value = random_array.min()
max_value = random_array.max()

print("10x10 array with random values: \n", random_array)
print()
print("minimum:", mini_value)
print("maximum", max_value)


10x10 array with random values: 
 [[0.62607767 0.08049067 0.59047405 0.18283115 0.83850227 0.08141944
  0.76906356 0.94645345 0.29712276 0.22388969]
 [0.06993928 0.66287657 0.04263055 0.65873958 0.34374512 0.22470095
  0.1582611  0.68708274 0.19080065 0.50865669]
 [0.60822309 0.28422287 0.13599642 0.98705426 0.61198156 0.10638518
  0.09355219 0.35562996 0.15168434 0.66838839]
 [0.62774396 0.8086807  0.41774127 0.43621676 0.34389485 0.49607127
  0.78468109 0.32841249 0.70880145 0.94533924]
 [0.41451136 0.71975366 0.41670823 0.70453233 0.96443724 0.48877778
  0.13273604 0.51153303 0.55122267 0.42453803]
 [0.32359592 0.8801862  0.12506235 0.99441911 0.02953748 0.30450451
  0.30361952 0.31132213 0.04759848 0.88740021]
 [0.31112318 0.5020527  0.73418196 0.45980313 0.56311122 0.84719189
  0.96186762 0.32391698 0.86917253 0.32197449]
 [0.26432244 0.20374293 0.24137368 0.86383966 0.94630302 0.3073239
  0.39208553 0.35994835 0.07189382 0.46892539]
 [0.64462644 0.64298679 0.64983491 0.92416183 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
vector = np.random.random(30)

mean_value = vector.mean()

print("Random vector of size 30: ", vector)
print("Mean value:", mean_value)

Random vector of size 30:  [0.42716931 0.09816641 0.19261759 0.81179943 0.57661799 0.94024049
 0.58182896 0.51152523 0.56109732 0.28792268 0.38426658 0.05428739
 0.55900156 0.58188131 0.51192042 0.09412626 0.32918737 0.20460162
 0.91259559 0.29940281 0.72103301 0.34769701 0.56861699 0.04265354
 0.35037168 0.88604786 0.50657757 0.93665717 0.35489985 0.57760257]
Mean value: 0.4737471178738967


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
two_D_array = np.ones([5, 5])
two_D_array[1: -1, 1: -1] = 0

print(two_D_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
# np.pad()

array = np.ones([5, 5])
array = np.pad(array, pad_width=1, mode="constant", constant_values=0)

print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
first_result = 0 * np.nan
second_result = np.nan == np.nan
third_result = np.inf > np.nan
forth_result = np.nan - np.nan
fifth_result = np.nan in set([np.nan])
sixth_result = 0.3 == 3 * 0.1

print(first_result)
print(second_result)
print(third_result)
print(forth_result)
print(fifth_result)
print(sixth_result)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
""" np.diag() """

matrix = np.diag(1 + np.arange(4), k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
matrix = np.zeros([8, 8], dtype = int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
array = np.unravel_index(100, [6, 7, 8])

print(array)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
checkerboard_array = np.tile(np.array([[0,1],[1,0]]), (4,4))

print(checkerboard_array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
random_array = np.random.random([5, 5])
random_array = (random_array - np.mean(random_array)) / np.std(random_array)

print(random_array)

[[-1.73763737  0.17017002 -0.81942364  0.78154513  0.00403069]
 [ 1.48762864  1.09943367  1.7385145   0.897815   -0.25999478]
 [-1.70751758 -0.12631357  1.0843005   0.99930905 -1.30485394]
 [-0.08376351  1.1528326  -0.69766379 -1.11821157  0.1288127 ]
 [-0.76548938 -1.00597944 -1.06871909  0.73439996  0.41677522]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
five_by_three_matrix = np.ones([5, 3])
three_by_two_matrix = np.ones([3, 2])
ans = np.dot(five_by_three_matrix, three_by_two_matrix)

print(ans)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
array = np.arange(11)
array[(3 < array) & (array <= 8)] *= -1

print(array)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5), -1))

from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(11)

Z**Z        # ValueError: Integers to negative integer powers are not allowed.
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
array = np.random.uniform(-10, +10, 10)
print (np.copysign(np.ceil(np.abs(array)), array))

[ -2.   9.  10.   1. -10.  -8.   7.   7.  -6.  -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
array_one = np.random.randint(0, 10, 10)
array_two = np.random.randint(0, 10, 10)

print(np.intersect1d(array_one, array_two))

[2 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
""" Suicide mode on """

defaults = np.seterr(all= "ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (2548505673.py, line 9)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("yesterday:", yesterday)
print("today:", today)
print("tomorrow:", tomorrow)

yesterday: 2022-10-14
today: 2022-10-15
tomorrow: 2022-10-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
random_array = np.random.uniform(0, 10, 10)

print(random_array - random_array % 1)
print(np.floor(random_array))
print(np.ceil(random_array) - 1)
print(random_array.astype(int))
print(np.trunc(random_array))

[1. 4. 0. 1. 2. 8. 0. 4. 2. 4.]
[1. 4. 0. 1. 2. 8. 0. 4. 2. 4.]
[1. 4. 0. 1. 2. 8. 0. 4. 2. 4.]
[1 4 0 1 2 8 0 4 2 4]
[1. 4. 0. 1. 2. 8. 0. 4. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
five_by_five_matrix = np.zeros([5, 5])
five_by_five_matrix += np.arange(5)

print(five_by_five_matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate() :
    for i in range(10) :
        yield i     # it will remember the last result.

array = np.fromiter(generate(), dtype = float, count = -1)

print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
vector = np.linspace(0, 1, 11, endpoint = False) [1:]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
random_vector = np.random.random(10)
random_vector.sort()

print(random_vector)

[0.29562631 0.30141455 0.36232685 0.68104718 0.74139418 0.76296562
 0.81938755 0.88649027 0.89378551 0.89770603]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
small_array = np.arange(10)

np.add.reduce(small_array)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
array_A = np.random.randint(0, 2, 5)
array_B = np.random.randint(0, 2, 5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(array_A, array_B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(array_A, array_B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
array = np.ones(10)
array.flags.writeable = False

array[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
random_10x2_matrix = np.random.random([10, 2])
X, Y = random_10x2_matrix[:, 0], random_10x2_matrix[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)

print(R)
print(T)

[1.01480681 1.30434779 0.85678743 1.01987702 0.7821137  0.58756283
 0.06197266 0.45457994 0.82275839 0.74737707]
[0.71001343 0.7024462  0.22504653 0.54472016 0.7278704  0.76522205
 0.64773266 0.34027314 1.47003985 0.0988668 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0

print(random_vector)

[0.53962518 0.12265965 0.53046465 0.37737009 0.27043392 0.09548846
 0.5201836  0.11351569 0.         0.31225641]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
structured_array = np.zeros([5, 5], [('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 5), 
                                                           np.linspace(0, 1, 5))

print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
array_X = np.arange(8)
array_Y = array_X + 0.5

cauchy_matrix_C = 1.0 / np.subtract.outer(array_X, array_Y)

print(np.linalg.det(cauchy_matrix_C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
# np.set_printoptions(threshold = np.nan)
array = np.zeros([16, 16])

print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
vector = np.arange(100)
given_scalar = np.random.uniform(0,100)
index = (np.abs(vector - given_scalar)).argmin()

print(vector[index])

89


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
structured_array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                                                ('y', float, 1)]),
                                                 ('color',    [ ('r', float, 1),
                                                                ('g', float, 1),
                                                                ('b', float, 1)])])
print(structured_array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/2852028742.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structured_array = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
vector = np.random.random([10, 2])
X, Y = np.atleast_2d(vector[:, 0], vector[:, 1])
distance = np.sqrt((X - X.T) ** 2 + (Y - Y.T) ** 2)

print(distance)

[[0.         0.24029605 0.32399006 0.71564143 0.93297548 0.82540135
  0.43899618 0.34184506 0.7152065  0.59269309]
 [0.24029605 0.         0.08725422 0.71089224 0.9037871  0.82751851
  0.25976581 0.2457727  0.52347733 0.71314615]
 [0.32399006 0.08725422 0.         0.70016494 0.87984911 0.81646117
  0.19857207 0.23322368 0.44611709 0.74710704]
 [0.71564143 0.71089224 0.70016494 0.         0.22320876 0.11668597
  0.54352183 0.46871989 0.58636437 0.37193499]
 [0.93297548 0.9037871  0.87984911 0.22320876 0.         0.14674762
  0.7012423  0.65801473 0.65976675 0.56034412]
 [0.82540135 0.82751851 0.81646117 0.11668597 0.14674762 0.
  0.65628176 0.58533801 0.67469124 0.41378945]
 [0.43899618 0.25976581 0.19857207 0.54352183 0.7012423  0.65628176
  0.         0.14569445 0.27636644 0.67752136]
 [0.34184506 0.2457727  0.23322368 0.46871989 0.65801473 0.58533801
  0.14569445 0.         0.39549942 0.541881  ]
 [0.7152065  0.52347733 0.44611709 0.58636437 0.65976675 0.67469124
  0.27636644 0.39549

In [41]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

vector = np.random.random((10,2))
distance = scipy.spatial.distance.cdist(vector,vector)
print(distance)

[[0.         0.22043881 0.38177034 0.62737191 0.57757747 0.16906734
  0.43876016 0.26697891 0.32683113 0.22569134]
 [0.22043881 0.         0.38495759 0.8471298  0.59167518 0.18099428
  0.47892191 0.33198389 0.47745185 0.20483195]
 [0.38177034 0.38495759 0.         0.84390601 0.20827669 0.50292432
  0.10538827 0.638605   0.28225688 0.18489065]
 [0.62737191 0.8471298  0.84390601 0.         0.94010706 0.72973977
  0.81824157 0.67954201 0.57195806 0.79295728]
 [0.57757747 0.59167518 0.20827669 0.94010706 0.         0.70928633
  0.14270367 0.84058992 0.37522093 0.3931592 ]
 [0.16906734 0.18099428 0.50292432 0.72973977 0.70928633 0.
  0.57848997 0.15230503 0.49521505 0.32123207]
 [0.43876016 0.47892191 0.10538827 0.81824157 0.14270367 0.57848997
  0.         0.70404621 0.24647596 0.27434088]
 [0.26697891 0.33198389 0.638605   0.67954201 0.84058992 0.15230503
  0.70404621 0.         0.57929104 0.46308664]
 [0.32683113 0.47745185 0.28225688 0.57195806 0.37522093 0.49521505
  0.24647596 0.57929

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
array = np.arange(10, dtype = np.float32)
array = array.astype(np.int32, copy = False)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO

# Fake file 
data = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

temp = np.genfromtxt(data, delimiter = ",", dtype = np.int)
print(temp)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_26533/3414768419.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  temp = np.genfromtxt(data, delimiter = ",", dtype = np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
array = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(array):
    print(index, value)
    
for index in np.ndindex(array.shape):
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
distance = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-((distance - mu) ** 2 / ( 2.0 * sigma ** 2)))

print(gaussian)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
col, row = 10, 10
num = 5
array = np.zeros([col, row])

np.put(array, np.random.choice(range(col * row), num, replace = False), 1)

print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
# recent version
array = np.random.rand(5, 10)

subtract_mean = array - array.mean(axis = 1, keepdims = True)

print(subtract_mean)

[[ 0.35543975 -0.02344299  0.26107238  0.29550172 -0.42486485  0.27156897
  -0.34681225  0.05375877 -0.20559634 -0.23662518]
 [-0.10468723  0.3823732   0.37726256 -0.48295392  0.14587432  0.2950408
  -0.04946427  0.31192313 -0.31523999 -0.5601286 ]
 [-0.29484658 -0.24449515  0.3848488   0.25668285 -0.19097089  0.0557127
   0.16782351  0.22908705 -0.2607475  -0.10309477]
 [-0.08347599  0.29502018  0.01923124  0.26555882  0.01772633 -0.15797039
  -0.42014829  0.2603763   0.06712599 -0.26344418]
 [-0.19445156 -0.34462517 -0.04126435  0.06141782 -0.09587959  0.40090326
  -0.12515436  0.27709771 -0.09134199  0.15329822]]


In [60]:
# previous version
array = np.random.rand(5, 10)

subtract_mean = array - array.mean(axis = 1).reshape(-1, 1)

print(subtract_mean)

[[-0.30407445  0.18418523  0.30697399 -0.16387172  0.37160198  0.25246537
  -0.33450473 -0.10302847 -0.0103291  -0.1994181 ]
 [ 0.22719946  0.24299888  0.22278301  0.26718793  0.098115   -0.29265
  -0.52981926 -0.10629027  0.36139209 -0.49091686]
 [ 0.12868067 -0.43171272 -0.17262437  0.4364527  -0.26787606  0.04463495
  -0.01473283  0.14708603 -0.1215337   0.25162533]
 [-0.29845139 -0.34069868  0.11572804 -0.35197856 -0.02073298  0.30611059
  -0.11179879  0.49613637 -0.31972156  0.52540696]
 [-0.04923516 -0.06121467 -0.20767324 -0.20594452 -0.2540287   0.18620687
  -0.4001725   0.09038074  0.36999351  0.53168767]]


#### 59. How to sort an array by the nth column? (★★☆)

In [61]:
array = np.random.randint(0, 10, [3, 3])

print(array)
print(array[array[:, 1].argsort()])

[[1 1 0]
 [2 5 5]
 [0 7 4]]
[[1 1 0]
 [2 5 5]
 [0 7 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
two_D_array = np.random.randint(0, 3, [3, 10])

print((~two_D_array.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [63]:
array = np.random.uniform(0, 1, 10)
given_value = 0.5
nearest_value = array.flat[np.abs(array - given_value).argmin()]

print(nearest_value)

0.46814223654813436


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [64]:
array_one = np.arange(3).reshape(3, 1)
array_two = np.arange(3).reshape(1, 3)
iter = np.nditer([array_one, array_two,None])

for x, y, z in iter: z[...] = x + y

print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
class NamedArray(np.ndarray) :
    def __new__(cls, array, name="no name") :
        obj = np.asarray(array).view(cls)
        obj.name = name
        
        return obj
    def __array_finalize__(self, obj) :
        if obj is None: return

        self.info = getattr(obj, 'name', "no name")

array = NamedArray(np.arange(10), "range_10_array")
print (array.name)

range_10_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
given_vector = np.ones(10)
second_vector = np.random.randint(0, len(given_vector), 20)
given_vector += np.bincount(second_vector, minlength=len(given_vector))

print(given_vector)

np.add.at(given_vector, second_vector, 1)

print(given_vector)

[3. 3. 3. 2. 3. 6. 2. 1. 4. 3.]
[ 5.  5.  5.  3.  5. 11.  3.  1.  7.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
vector_X = [1, 2, 3, 4, 5, 6]
list_I = [1, 3, 9, 3, 4, 1]
array_F = np.bincount(list_I, vector_X)

# index[0,       1, 2,       3, 4, 5, 6, 7, 8, 9]
# value[0, (1 + 6), 0, (2 + 4), 5, 0, 0, 0, 0, 3]

print(array_F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [68]:
""" Not solved """

w, h = 16,16
I = np.random.randint(0, 2, [h, w, 3]).astype(np.ubyte)

# Note that we should compute 256*256 first. 
# Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[..., 0] * (256 * 256) + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))

print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [69]:
# Solved by passing a tuple of axes.

four_D_array = np.random.randint(0, 10, [3, 4, 3, 4])

sum = four_D_array.sum(axis=(-2, -1))

print(sum)

[[62 58 65 52]
 [56 75 57 36]
 [48 46 57 56]]


In [70]:
# Solved by flattening the last two dimensions into one
# (useful for the funcitons that don't accept tuples for axis argument)

four_D_array = np.random.randint(0, 10, [3, 4, 3, 4])

sum = four_D_array.reshape(four_D_array.shape[: -2] + (-1,)).sum(axis=-1)

print(sum)

[[64 52 58 39]
 [48 60 48 66]
 [53 55 45 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [71]:
vector_D = np.random.uniform(0, 1, 100)
vector_S = np.random.randint(0, 10, 100)
D_sums = np.bincount(vector_S, weights=vector_D)
D_counts = np.bincount(vector_S)
D_means = D_sums / D_counts

print(D_means)

[0.54754587 0.39388915 0.3327026  0.62895303 0.48546537 0.40740459
 0.54345822 0.38823593 0.44123963 0.27339627]


In [64]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd

vector_D = np.random.uniform(0, 1, 100)
vector_S = np.random.randint(0, 10, 100)

print(pd.Series(vector_D).groupby(vector_S).mean())

0    0.575582
1    0.455774
2    0.539492
3    0.387502
4    0.522761
5    0.441763
6    0.492917
7    0.509713
8    0.518175
9    0.546769
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [72]:
A = np.random.uniform(0, 1, [5, 5])
B = np.random.uniform(0, 1, [5, 5])

# Slow version  
np.diag(np.dot(A, B))

array([1.09476188, 1.64204055, 0.68385469, 1.53101684, 0.87922222])

In [73]:
A = np.random.uniform(0, 1, [5, 5])
B = np.random.uniform(0, 1, [5, 5])

# Fast version
np.sum(A * B.T, axis=1)

array([0.69906508, 1.95701278, 0.38913155, 0.92008629, 1.20226372])

In [74]:
A = np.random.uniform(0, 1, [5, 5])
B = np.random.uniform(0, 1, [5, 5])

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.68769703, 0.8351146 , 1.76459289, 1.56431094, 1.57145829])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [75]:
vector = np.array([1, 2, 3, 4, 5])
num = 3
new_vector = np.zeros(len(vector) + (len(vector) -1 ) * num)
new_vector[:: num + 1] = vector

print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [76]:
three_D_array = np.ones([5, 5, 3])
two_D_array = 2 * np.ones([5, 5])
ans = three_D_array * two_D_array[:, :, None]

print(ans)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [77]:
array = np.arange(25).reshape(5, 5)
array[[0, 1]] = array[[1, 0]]

print(array)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
""" Not solved """

faces = np.random.randint(0, 100, [10,3])
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)

print(G)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [78]:
sorted_array_C = np.bincount([1, 1, 2, 3, 4, 4, 5, 6, 7])
len = len(sorted_array_C)
array_A = np.repeat(np.arange(len), sorted_array_C)

print(array_A)

[1 1 2 3 4 4 5 6 7]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [79]:
def computeAverage(array, n = 3) :
    ret = np.cumsum(array, dtype=float)
    ret[n:] = ret[n:] - ret[: -n]

    return ret[n - 1:] / n

array = np.arange(20)

print(computeAverage(array, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [80]:
""" Not solved """

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)

    return stride_tricks.as_strided(a, shape=shape, strides=strides)


array_Z = rolling(np.arange(10), 3)
print(array_Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [83]:
array = np.random.randint(0, 2, 100)
np.logical_not(array, out=array)

array = np.random.uniform(-1.0, 1.0, 100)
np.negative(array, out=array)

array([ 0.99913779,  0.79386256, -0.89729962, -0.76583531, -0.60534293,
        0.95152654,  0.72729776,  0.52766537,  0.9534956 , -0.75372934,
        0.6791922 , -0.83432521, -0.50883215,  0.68565346, -0.92669705,
       -0.78266704,  0.60683714, -0.21908474, -0.71868286,  0.8652204 ,
        0.61532246,  0.82397995,  0.81556342, -0.62508925,  0.6049021 ,
       -0.35962286,  0.04265951, -0.75525767, -0.1537657 , -0.53902637,
        0.6374029 ,  0.80867738, -0.35726019,  0.50371729,  0.13991203,
        0.35737909, -0.80541636, -0.85437521, -0.67103727,  0.4045015 ,
       -0.53603691,  0.36193741,  0.91100209,  0.65353162, -0.99303766,
        0.19934032, -0.77528118, -0.05210761,  0.02020122, -0.65153299,
        0.06927859, -0.30367939, -0.56621703,  0.46919785,  0.73765818,
        0.01946204,  0.52619272, -0.82457508,  0.25588007,  0.95702093,
        0.0534091 , -0.31149363, -0.79860325,  0.94091844, -0.38281201,
        0.46464667,  0.49148894, -0.84903888,  0.91039676, -0.52

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [3]:
def countDistance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U_len = U.reshape(len(U), 1)
    D = P0 + U_len * T - p

    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, [10, 2])
P1 = np.random.uniform(-10, 10, [10, 2])
p  = np.random.uniform(-10, 10, [ 1, 2])
print(countDistance(P0, P1, p))

[ 6.92422781  1.12589728  3.78752423  0.31454582 15.44805471  5.70076619
  7.52861777 10.54098953  2.36918472 14.09782301]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [4]:
def countDistance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U_len = U.reshape(len(U), 1)
    D = P0 + U_len * T - p

    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))

print(np.array([countDistance(P0,P1,p_i) for p_i in p]))

[[ 3.90686561  3.55892486  0.90514854  4.6512374   2.67050748  3.77916724
   3.25865999  1.60096664  2.08966725  8.68937981]
 [ 8.43909574  9.41063883 11.41394911  6.38971614  6.6742545  15.3681237
   4.12401978  3.82130908 10.06780506  0.3429023 ]
 [ 0.90862974  0.25795034  1.93972433  3.44874189  2.5327468  15.13977848
   4.02079403  8.72624634  9.17263124  2.46821546]
 [ 4.15794907  2.29707794  4.42926637  0.26360625  2.61517104 11.33283227
   1.44978163  3.39646407  5.64314388  2.38043232]
 [ 3.37022781  4.82099262  2.97166754  8.00101869  4.81332372 11.48934922
   5.20108477  7.57798813  5.26990355  0.1714537 ]
 [10.44122847  0.62112291  3.70928793  0.59598908  9.22614841  0.95486876
   9.75378122  7.0574994   4.5115752  13.1785387 ]
 [ 1.18283533  1.83563018  3.33348849  2.38044472  2.90241573 17.61678613
   4.92696332 10.55801343 11.68313657  4.65164285]
 [ 1.99331527  4.19801955  5.87577538  0.41305265  0.26624336 16.68874707
   1.88937327  8.2080173  10.96018837  2.84582859]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [5]:
Z = np.random.randint(0, 10, [10, 10])
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 6 9 9 5 5 2 1 5 9]
 [6 7 5 7 4 4 2 7 4 8]
 [6 3 9 8 6 4 3 8 7 5]
 [6 3 6 2 6 1 1 6 5 7]
 [1 4 3 8 7 6 5 0 5 3]
 [8 1 7 3 1 4 2 6 2 7]
 [8 0 1 2 1 4 4 4 2 2]
 [3 6 0 8 2 5 3 3 8 3]
 [4 6 7 0 7 6 2 3 3 2]
 [9 5 4 8 9 6 1 2 6 0]]
[[0 0 0 0 0]
 [0 3 6 9 9]
 [0 6 7 5 7]
 [0 6 3 9 8]
 [0 6 3 6 2]]


/var/folders/nl/l2b2vttd7j73mhvfwrp0lwzr0000gn/T/ipykernel_36851/638444530.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [7]:
from numpy.lib import stride_tricks

array_Z = np.arange(1, 15, dtype=np.uint32)
array_R = stride_tricks.as_strided(array_Z, [11,4], [4,4])

print(array_R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [8]:
matrix = np.random.uniform(0, 1, [10, 10])
U, S, V = np.linalg.svd(matrix) # Singular Value Decomposition
rank = np.sum(S > 1e-10)

print(rank)

10


#### 83. How to find the most frequent value in an array?

In [10]:
array = np.random.randint(0, 10, 50)
most_frequent_value = np.bincount(array).argmax()

print(array)
print(most_frequent_value)

[8 8 4 2 4 3 1 7 1 7 1 7 2 3 3 9 6 1 6 3 1 0 0 8 0 9 1 0 4 7 2 7 2 8 3 1 5
 4 8 0 4 1 1 9 7 0 4 2 1 9]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [11]:
array = np.random.randint(0, 5, [10, 10])
n = 3
i = 1 + (array.shape[0] - 3)
j = 1 + (array.shape[1] - 3)
C = stride_tricks.as_strided(array, shape=(i, j, n, n), 
                             strides=array.strides + array.strides)

print(C)

[[[[0 1 4]
   [2 2 3]
   [0 1 2]]

  [[1 4 2]
   [2 3 1]
   [1 2 4]]

  [[4 2 3]
   [3 1 2]
   [2 4 0]]

  [[2 3 3]
   [1 2 0]
   [4 0 2]]

  [[3 3 0]
   [2 0 1]
   [0 2 0]]

  [[3 0 4]
   [0 1 3]
   [2 0 1]]

  [[0 4 4]
   [1 3 2]
   [0 1 0]]

  [[4 4 2]
   [3 2 0]
   [1 0 0]]]


 [[[2 2 3]
   [0 1 2]
   [4 0 3]]

  [[2 3 1]
   [1 2 4]
   [0 3 1]]

  [[3 1 2]
   [2 4 0]
   [3 1 2]]

  [[1 2 0]
   [4 0 2]
   [1 2 2]]

  [[2 0 1]
   [0 2 0]
   [2 2 0]]

  [[0 1 3]
   [2 0 1]
   [2 0 0]]

  [[1 3 2]
   [0 1 0]
   [0 0 1]]

  [[3 2 0]
   [1 0 0]
   [0 1 2]]]


 [[[0 1 2]
   [4 0 3]
   [2 4 2]]

  [[1 2 4]
   [0 3 1]
   [4 2 1]]

  [[2 4 0]
   [3 1 2]
   [2 1 2]]

  [[4 0 2]
   [1 2 2]
   [1 2 1]]

  [[0 2 0]
   [2 2 0]
   [2 1 0]]

  [[2 0 1]
   [2 0 0]
   [1 0 0]]

  [[0 1 0]
   [0 0 1]
   [0 0 2]]

  [[1 0 0]
   [0 1 2]
   [0 2 2]]]


 [[[4 0 3]
   [2 4 2]
   [4 1 2]]

  [[0 3 1]
   [4 2 1]
   [1 2 4]]

  [[3 1 2]
   [2 1 2]
   [2 4 4]]

  [[1 2 2]
   [1 2 1]
   [4 4 1]]

  [[2 2 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [14]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

array = np.random.randint(0, 10, [5, 5])
symetric_array = symetric(array)
symetric_array[2, 3] = 42

print(symetric_array)

[[ 9 10  6 10 14]
 [10  0 15 10  7]
 [ 6 15  9 42 16]
 [10 10 42  4  8]
 [14  7 16  8  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [15]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [16]:
array = np.ones([16, 16])
size = 4
block_sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], size), axis=0),
                                       np.arange(0, array.shape[1], size), axis=1)

print(block_sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [17]:
def iterate(array) :
    # Count neighbours
    neighbours = (array[0: -2, 0: -2] + array[0: -2, 1: -1] + array[0: -2, 2:] +
                  array[1: -1, 0: -2]                       + array[1: -1, 2:] +
                  array[2:   , 0: -2] + array[2:   , 1: -1] + array[2:   , 2:]   )

    # Apply rules
    birth = (neighbours == 3) & (array[1: -1, 1: -1] == 0)
    survive = ((neighbours == 2) | (neighbours == 3)) & (array[1: -1, 1: -1] == 1)
    array[...] = 0
    array[1: -1, 1: -1][birth | survive] = 1
    
    return array

array = np.random.randint(0,2,[50,50])
for i in range(100) : array = iterate(array)

print(array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [18]:
array = np.arange(10000)
np.random.shuffle(array)
n = 5

# Slow
print (array[np.argsort(array)[-n:]])

# Fast
print (array[np.argpartition(-array, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [19]:
def cartesian(arrays) :
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays) :
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [20]:
array = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
regular_array = np.core.records.fromarrays(array.T,
                               names = 'col1, col2, col3',
                               formats = 'S8, f8, i8')
print(regular_array)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [21]:
vector_Z = np.random.rand(int(5e7))

%timeit np.power(vector_Z, 3)
%timeit vector_Z * vector_Z * vector_Z
%timeit np.einsum('i,i,i->i', vector_Z, vector_Z, vector_Z)

1.48 s ± 525 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
338 ms ± 45.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
336 ms ± 100 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [22]:
array_A = np.random.randint(0, 5, [8, 3])
array_B = np.random.randint(0, 5, [2, 2])

C = (array_A[..., np.newaxis, np.newaxis] == array_B)
rows = np.where(C.any((3, 1)).all(1))[0]

print(rows)

[1 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [23]:
# solution for arrays of all dtypes (including string arrays and record arrays)

ten_by_three_matrix = np.random.randint(0, 5, [10, 3])

print(ten_by_three_matrix)

E = np.all(ten_by_three_matrix[:, 1:] == ten_by_three_matrix[:, : -1], axis=1)
U = ten_by_three_matrix[~E]
print(U)


[[0 3 0]
 [0 0 3]
 [3 4 2]
 [4 3 3]
 [4 1 4]
 [2 0 3]
 [4 1 2]
 [2 3 3]
 [2 1 3]
 [3 2 0]]
[[0 3 0]
 [0 0 3]
 [3 4 2]
 [4 3 3]
 [4 1 4]
 [2 0 3]
 [4 1 2]
 [2 3 3]
 [2 1 3]
 [3 2 0]]


In [24]:
# soluiton for numerical arrays only, will work for any number of columns in ten_by_three_matrix

ten_by_three_matrix = np.random.randint(0, 5, [10, 3])

print(ten_by_three_matrix)

U = ten_by_three_matrix[ten_by_three_matrix.max(axis=1) != ten_by_three_matrix.min(axis=1),:]
print(U)

[[4 4 3]
 [1 4 2]
 [4 2 2]
 [0 0 3]
 [3 4 4]
 [4 0 1]
 [3 3 0]
 [0 4 1]
 [0 3 3]
 [1 3 4]]
[[4 4 3]
 [1 4 2]
 [4 2 2]
 [0 0 3]
 [3 4 4]
 [4 0 1]
 [3 3 0]
 [0 4 1]
 [0 3 3]
 [1 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [26]:
vector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
binary_representation = ((vector.reshape(-1, 1) & (2 ** np.arange(8))) != 0).astype(int)

print(binary_representation[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [27]:
vector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(vector[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [33]:
array = np.random.randint(0, 2, [6, 3])
T = np.ascontiguousarray(array).view(np.dtype((np.void, array.dtype.itemsize * array.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = array[idx]

print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


In [32]:
# Author: Andreas Kouarrayelis
# NumPy >= 1.13

array = np.random.randint(0, 2, [6, 3])
T = np.ascontiguousarray(array).view(np.dtype((np.void, array.dtype.itemsize * array.shape[1])))
_, idx = np.unique(T, return_index=True)
uarray = np.unique(array, axis=0)

print(uarray)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [34]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

vector_A = np.random.uniform(0, 1, 10)
vector_B = np.random.uniform(0, 1, 10)

np.einsum('i->',    vector_A          ) # np.sum(A)
np.einsum('i,i->i', vector_A, vector_B) # A * B
np.einsum('i,i',    vector_A, vector_B) # np.inner(A, B)
np.einsum('i,j->ij',vector_A, vector_B) # np.outer(A, B)

array([[2.16638264e-01, 2.04944846e-01, 1.84874635e-01, 2.16897131e-01,
        2.49206136e-01, 7.46309464e-02, 1.59650227e-01, 1.53041200e-01,
        1.58382165e-02, 3.38591452e-02],
       [3.39632169e-04, 3.21299947e-04, 2.89835102e-04, 3.40038005e-04,
        3.90690080e-04, 1.17001816e-04, 2.50289824e-04, 2.39928597e-04,
        2.48301834e-05, 5.30822890e-05],
       [6.85876236e-01, 6.48854903e-01, 5.85312662e-01, 6.86695808e-01,
        7.88986044e-01, 2.36281401e-01, 5.05452244e-01, 4.84528080e-01,
        5.01437563e-02, 1.07197974e-01],
       [6.52474162e-01, 6.17255762e-01, 5.56808019e-01, 6.53253821e-01,
        7.50562537e-01, 2.24774531e-01, 4.80836793e-01, 4.60931633e-01,
        4.77017626e-02, 1.01977449e-01],
       [5.11985162e-01, 4.84349894e-01, 4.36917599e-01, 5.12596947e-01,
        5.88953409e-01, 1.76376677e-01, 3.77304294e-01, 3.61685060e-01,
        3.74307460e-02, 8.00199357e-02],
       [5.32235863e-01, 5.03507530e-01, 4.54199130e-01, 5.32871846e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [35]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
vectors_X = a * phi * np.cos(phi)
vectors_Y = a * phi * np.sin(phi)

dr = (np.diff(vectors_X)**2 + np.diff(vectors_Y)**2)**.5 # segment lengths
r = np.zeros_like(vectors_X)
r[1:] = np.cumsum(dr)                        # integrate path
r_int = np.linspace(0, r.max(), 200)         # regular spaced path
x_int = np.interp(r_int, r, vectors_X)       # integrate path
y_int = np.interp(r_int, r, vectors_Y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [36]:
two_D_array_X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(two_D_array_X, 1) == 0, axis=-1)
M &= (two_D_array_X.sum(axis=-1) == n)

print(two_D_array_X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [37]:
one_D_array_X = np.random.randn(100) # random 1D array
N = 1000                             # number of bootstrap samples
idx = np.random.randint(0, one_D_array_X.size, (N, one_D_array_X.size))
means = one_D_array_X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.09524975  0.3090856 ]
